name: Test Exercise 2

on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 black

    - name: Lint with flake8
      run: |
        flake8 day5/演習2 --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 day5/演習2 --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Format check with black
      run: |
        black --check day5/演習2

    - name: Run pytest on main.py
      run: |
        pytest day5/演習2/main.py -v
